### ISSUE TITLE
DeprecationWarning: Buffer(), DeprecationWarning: crypto.createCipher

### ISSUE THREAD

**Issue by computersalat** [wemove/read2burn#13]
Hi,
getting  this:

```
(node:4070) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node-default --trace-deprecation ...` to show where the warning was created)
(node:4070) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
Inserted hmytekpt with ID ...
```

**Comment by joachimmueller** [comment]
Thanks for checking. I am aware about this and have a patch in work. Not as simple as I thought, because I dont want to loose existing entries, so the old encryption must still be supported.

**Comment by joachimmueller** [comment]
I refactored the code a bit to fix the security issues:

    Update libraries
    Update encryption method
    Validate request parameters
    Keep compatibility with older, existing entries

Please check out https://github.com/wemove/read2burn/releases/tag/0.7.0

**Comment by computersalat** [comment]
> I refactored the code a bit to fix the security issues:
> 
> ```
> Update libraries
> Update encryption method
> Validate request parameters
> Keep compatibility with older, existing entries
> ```
> 
> Please check out https://github.com/wemove/read2burn/releases/tag/0.7.0

works :+1: 
Thank you
