### ISSUE TITLE
Copyright and licensing information missing

### ISSUE THREAD

**Issue by ppxl** [wemove/read2burn#3]
Hi, I just stumbled over Read2Burn in a customer's environment and fell immediately in love with it. 

While considering to integrate it with another open source product, I noticed that here is no licensing or copyright information for this repository. Do I read this correctly that you maintain this repository as proprietary software with your full copyright? Or do you have plans to release it under an open source license like MIT, GPL etc.?

If you plan to maintain it as proprietary software, a note of this would also help. This way people get a better idea of how your repo could be used in the future.

Thanks in advance and keep up the good work!
Cheers

**Comment by joachimmueller** [comment]
Thanks for pointing this out. I just fixed it and add a Apache 2 License.
